dataset:
  csv_path: 'path/to/laion_audio.csv'
training:
  epochs: 5
  batch_size: 16
  learning_rate: 1e-5
  weight_decay: 0.01
  max_grad_norm: 1.0
  early_stopping_patience: 3
clap_training:
  epochs: 10
  batch_size: 8
  learning_rate: 1e-4
audiobert_training:
  epochs: 20
  batch_size: 4
  learning_rate: 3e-4
  max_grad_norm: 1.0
